### ISSUE TITLE
请教在 issue 中写博客的问题

### ISSUE THREAD

**Issue by hadeshe93** [mqyqingfeng/Blog#124]
@mqyqingfeng 首先很肯定博主的文章，虽然我还没有全部阅读完毕，但是我读过的每一篇都感觉思路很清晰，写得很棒。其次，想请教一下，博主在 issue 中写博客，那怎么保持之前发布过的文章有更新呢？

比如说，我在仓库里用 git 就能保证文章能够方便更新，那在 issue 里面，比如说前 3 个月发布的文章，今天我有修改，那么就需要单独地找到这个文章的 issue，然后重新修改吗？这样岂不是就要修改两个地方？
一个是仓库里的文章，一个是 issue 中的文章。

还请博主解惑，谢谢！

**Comment by Lamborshea** [comment]
只需要用自己喜欢的编辑器里写一份 markdown 文件保存即可，有更新只是复制粘贴的事情

**Comment by mqyqingfeng** [comment]
@hadeshe93 是的，你说的问题确实存在，我每次确实是手动更新的……有好的解决方案期待分享~
