### ISSUE TITLE
说实话，淘宝网站的技术水平不行

### ISSUE THREAD

**Issue by czl0325** [mqyqingfeng/Blog#151]
说实话，淘宝网站的技术水平不行

当淘宝网页点击跳转到天猫商品时候，用户无法登录！
请在mac10.15最新版本，safari最新版本上测试就知道了。

**Comment by mqyqingfeng** [comment]
哈哈，bug 超级多的，无法登录应该是前段时间的浏览器增加了 cookie 限制的缘故，淘宝已经有很多地方做改造了
