### ISSUE TITLE
给i赋值后，i变成了abc,  abc++<3不成立。所以直接结束循环

### ISSUE THREAD

**Issue by Moments28** [mqyqingfeng/Blog#160]
```js
for (var i = 0; i < 3; i++) {
  var i = 'abc';
  console.log(i);
}
// abc
```
这里为什么会只输出一个abc呢？？求教

_Originally posted by @brushbird in https://github.com/mqyqingfeng/Blog/issues/82#issuecomment-391196013_

**Comment by mqyqingfeng** [comment]
因为没有单独的作用域，第一遍循环的时候就修改了 i 的值为 abc，所以不会接着执行了
