### ISSUE TITLE
JavaScript 问题

### ISSUE THREAD

**Issue by GuiYe18** [mqyqingfeng/Blog#168]
> > > ```js
> > > for (var i = 0; i < 3; i++) {
> > >   var i = 'abc';
> > >   console.log(i);
> > > }
> > > // abc
> > > ```
> > > 
> > > 
> > > 这里为什么会只输出一个abc呢？？求教
> 
> 上面不是有人已经说过了吗，i = abc ，然后再++ 转化成 NaN ，小于 3

我也是这样想的，但是当执行`"abc"++`的时候，会报错的啊，并不能得出`NaN`。

_Originally posted by @ZhangDaZongWei in https://github.com/mqyqingfeng/Blog/issues/82#issuecomment-610359678_

**Comment by ItAzeY** [comment]
var a = "abc"
a++
console.log(a) // NaN

**Comment by w3cfed** [comment]
@GuiYe18 兄弟，这是个人博客。你要问问题，直接去对应额 issues 回复就好了。新开一个 issues，
@mqyqingfeng 同意了吗？

**Comment by w3cfed** [comment]
@GuiYe18 你这么搞。
![image](https://user-images.githubusercontent.com/51536312/79892536-4e4ca380-8435-11ea-8f99-cfb07f63e071.png)
有这么多人能收到邮件！

**Comment by Reconsole** [comment]
这个博客不能watch吗？如果不行的话，我取消了吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jack Wang"<notifications@github.com&gt;; 
发送时间: 2020年4月22日(星期三) 凌晨1:08
收件人: "mqyqingfeng/Blog"<Blog@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [mqyqingfeng/Blog] &gt; &gt; &gt; ```js (#168)





 
@GuiYe18 你这么搞。
 
 有这么多人能收到邮件！

**Comment by Reconsole** [comment]
不是很懂这个情况，对你造成不必要的麻烦，抱歉，我已经取消了watch了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jack Wang"<notifications@github.com&gt;; 
发送时间: 2020年4月22日(星期三) 凌晨1:06
收件人: "mqyqingfeng/Blog"<Blog@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [mqyqingfeng/Blog] &gt; &gt; &gt; ```js (#168)





 
@GuiYe18 兄弟，这是个人博客。你要问问题，直接去对应额 issues 回复就好了。新开一个 issues，
 @mqyqingfeng 同意了吗？

**Comment by mqyqingfeng** [comment]
@Reconsole 是这样的，不用新建一个 issue 的形式来讨论这个问题，可以直接在对应 issue 里评论回复的。 博客的 watch 相当于订阅，如果有回复或者新的 issue ，会邮件通知所有 watch 的同学，所以呢，你取消自己的 watch 是没有什么用的……不过这件事情也没有什么太大关系哈，不用介意，下次直接评论回复好了，如果真的需要新建 issue，至少 issue 的标题要写清楚~

**Comment by Reconsole** [comment]
可能是我不太懂github，只是觉得watch是关注，让自己方便查看，没有想到会有这些问题。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "冴羽"<notifications@github.com&gt;; 
发送时间: 2020年4月22日(星期三) 上午10:45
收件人: "mqyqingfeng/Blog"<Blog@noreply.github.com&gt;; 
抄送: "Doc"<1327061537@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [mqyqingfeng/Blog] JavaScript 问题 (#168)





 
@Reconsole 是这样的，不用新建一个 issue 的形式来讨论这个问题，可以直接在对应 issue 里评论回复的。 博客的 watch 相当于订阅，如果有回复或者新的 issue ，会邮件通知所有 watch 的同学，所以呢，你取消自己的 watch 是没有什么用的……不过这件事情也没有什么太大关系哈，不用介意，下次直接评论回复好了，如果真的需要新建 issue，至少 issue 的标题要写清楚~

**Comment by Reconsole** [comment]
可能是我不太懂github，只是觉得watch是关注，让自己方便查看，没有想到会有这些问题，也谢谢你这样耐心的回复。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "冴羽"<notifications@github.com&gt;; 
发送时间: 2020年4月22日(星期三) 上午10:45
收件人: "mqyqingfeng/Blog"<Blog@noreply.github.com&gt;; 
抄送: "Doc"<1327061537@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [mqyqingfeng/Blog] JavaScript 问题 (#168)





 
@Reconsole 是这样的，不用新建一个 issue 的形式来讨论这个问题，可以直接在对应 issue 里评论回复的。 博客的 watch 相当于订阅，如果有回复或者新的 issue ，会邮件通知所有 watch 的同学，所以呢，你取消自己的 watch 是没有什么用的……不过这件事情也没有什么太大关系哈，不用介意，下次直接评论回复好了，如果真的需要新建 issue，至少 issue 的标题要写清楚~
