### ISSUE TITLE
不知道是不是我的知识水平很低的关系，还是我的理解有问题。

### ISSUE THREAD

**Issue by puck1006** [mqyqingfeng/Blog#177]
不知道是不是我的知识水平很低的关系，还是我的理解有问题。
第六版(其实是从第四版开始)，不是只走 if 的分支吗(immediate 一直为ture)？
(我测试的结果是没有进入到else执行过)
望大佬回答我下，解答我心中的疑惑。
`
// 第六版
function debounce(func, wait, immediate) {

    var timeout, result;

    var debounced = function () {
        var context = this;
        var args = arguments;

        if (timeout) clearTimeout(timeout);
        if (immediate) {
            // 如果已经执行过，不再执行
            var callNow = !timeout;
            timeout = setTimeout(function(){
                timeout = null;
            }, wait)
            if (callNow) result = func.apply(context, args)
        }
        else {
            timeout = setTimeout(function(){
                func.apply(context, args)
            }, wait);
        }
        return result;
    };

    debounced.cancel = function() {
        clearTimeout(timeout);
        timeout = null;
    };

    return debounced;
}
`

_Originally posted by @fdjiangwu in https://github.com/mqyqingfeng/Blog/issues/22#issuecomment-651519910_

**Comment by lushevol** [comment]
是的, 如果设置了immediate=true就只会走if分支, 表示头执行. 为false走else分支.
区别就是, immediate会在事件第一次(和超时完成后第一次)时触发执行, 然后才开始计时.
immediate=false时会在事件出现时开始计时, 在计时完成后触发执行.
