### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Hackerstudent98** [mqyqingfeng/Blog#19]
Hi there 
I hope guys translate english

**Comment by jawil** [comment]
I guess you see this blog from this place that url may be https://github.com/trending/unknown

Top 10 trending GitHub repositories today!!!

@Hackerstudent98 Am I right?😄

**Comment by mqyqingfeng** [comment]
@jawil 看到你的 issues 里面也有人这样问你~~~哈哈~

**Comment by mqyqingfeng** [comment]
@Hackerstudent98 Hi, friend, It's tough for me to translate these articles to English. You can use Google translation or let your Chinese friends help you ~ 😉

If you have some questions，you can write in this issue，maybe I can help you.
