### ISSUE TITLE
关于执行上下文

### ISSUE THREAD

**Issue by bestvayne** [mqyqingfeng/Blog#29]
请问，执行上下文是不是意思：开始执行一段代码？

**Comment by mqyqingfeng** [comment]
@besvayne 我觉得更像是一种执行环境吧，以函数执行上下文为例，它包含了当前函数的变量对象以及规定了函数的内的变量可以访问到哪些变量对象。

**Comment by mqyqingfeng** [comment]
@bestvayne 对了，如果有疑问，可以直接在具体的文章下回复哈~ 这样以后有相同疑问的人也可以看到~

**Comment by bestvayne** [comment]
@mqyqingfeng 我最近在翻高程3的书，我可以不可以理解为，这个“执行上下文”其实就是js的引擎为一块代码块创建了一个执行环境，然后将这个代码块以栈的形式推入到了这个环境中。等这个代码块执行完毕，然后就销毁这个执行环境，然后将代码块推出。然后开始执行下一块代码？

**Comment by mqyqingfeng** [comment]
@bestvayne 我赞同你的观点哈~
