### ISSUE TITLE
Object.prototype.toString.call

### ISSUE THREAD

**Issue by xdwxls** [mqyqingfeng/Blog#31]
Object.prototype.toString  出来就是 "[object Object]"
Object.prototype.toString.call()  为什么加上call() 后 就能获取不同的类型？ 为什么？

**Comment by mqyqingfeng** [comment]
关于 Object.prototype.toString，我们来看下规范：

<img width="637" alt="default" src="https://user-images.githubusercontent.com/11458263/28079165-dcfb1632-6699-11e7-92f6-e457aed5b319.png">

我们会发现，该方法判断的其实是 this 的值，而非传入的函数的值。

如果我们在浏览器中直接使用该方法：

<img width="308" alt="default" src="https://user-images.githubusercontent.com/11458263/28079261-27fadadc-669a-11e7-8c28-89a54bca3c9c.png">

打印的结果之所以都是"[object Object]"，正是因为 this 的值是 window 对象。

而当我们使用 call 的时候，就是指定了 this  的值，自然就会根据规范来得出正确的结果~
