### ISSUE TITLE
构造函数的prototype指向实例的原型的问题

### ISSUE THREAD

**Issue by kaka709682** [mqyqingfeng/Blog#48]
请教博主，其实有一点不是很明白，就是文中说“构造函数的prototype指向实例的原型”，可是构造函数的prototype不是本身是一个值为对象的属性吗？我之前只是知道，实例的_protote_属性会指向构造函数的原型的prototype,实例在查找属性或者方法时，如果找不到的话，就会通过_protote_到它的构造函数的prototype对象上去找，所有的实例共享它的构造函数上的prototype的属性和方法。但是如果照博主的说法，构造函数的prototype指向实例的原型，那如果实例有很多，它到底指向的是哪一个实例的原型呢，不同实例的属性和方法如何做到共享。但是如果按照我这种说法，文中的案例：
![image](https://user-images.githubusercontent.com/20055848/30306745-97b3f3b6-97ac-11e7-93cc-cf6367644833.png)
实例化之后改变了Person 的prototype后，实例一其实是可以访问到getName这个方法的，所以这就有了矛盾，可能我的理解有误，但是博主这里讲的我也不是很懂，望不吝赐教！

**Comment by mqyqingfeng** [comment]
我们以这张图为例：
![原型关系图](https://raw.githubusercontent.com/mqyqingfeng/Blog/master/Images/prototype3.png)

准确的说，实例的 \_\_proto\_\_(是 \_\_proto\_\_不是 \_\_protote\_\_ 哈~) 和 Person.prototype 都指向一个对象，这个对象就是实例的原型对象，实例在查找属性或者方法的时候，如果找不到，就会到该实例的原型对象中进行查找，同一个构造函数的所有实例都指向一个原型对象，如果你不修改它的话。

为了更好的理解图中的例子，我们需要先了解下 new 的工作原理，在 [《JavaScript深入之new的模拟实现》](https://github.com/mqyqingfeng/Blog/issues/13) 中有详细的介绍，我们直接看最后的代码：

```js
function objectFactory() {

    var obj = new Object(),

    Constructor = [].shift.call(arguments);

    obj.__proto__ = Constructor.prototype;

    var ret = Constructor.apply(obj, arguments);

    return typeof ret === 'object' ? ret : obj;

};
```

当使用 new 的时候，步骤如下：
1. 创建新对象
2. 设置该对象的原型对象为构造函数的 prototype
3. 将 this 指向新对象，这一步使用了 apply，表明函数此时会被执行一遍
4. 返回新对象

我们再看文中的这个例子：

当执行 var person1 = new Person('kevin') 的时候，按照以上所说的执行步骤，就会创建一个新对象，假设就叫  obj 吧，然后就将 obj 的原型设置为 person.prototype 所指向的那个对象，我们命名为 O 吧，然后我们才将 this 指向 obj，这个过程中，我们会执行函数中的内容，也就会更改 Person.prototype，可是我们已经将 obj 的原型对象指向了 O，更改 Person.prototype 也不会改变这个关系了，只能对下一个 new 的对象才会生效，我们再简化下这个过程:

```js
// {value: 1} 相当于原型对象 , obj.a 指向 {value: 1}，就像 Person.prototype 指向原型对象
var obj = {
    a: {value: 1}
}

var b = {}
b.protoValue = obj.a; // 相当于设置了实例的 __proto__ 为 Person.protoype

obj.a = {value: 2} // 相当于你更改了 Person.prototype
console.log(b.protoValue) // {value: 1} // 即便你更改了 Person.prototype，已经建立的关系无法被删除

var c = {}
c.protoValue = obj.a;
console.log(c.protoValue) // {value: 2} // 对下一个才会生效
```

所以文中的这个例子，person1 的 __proto__ 还是指向更改之前的 Person.prototype 指向的那个对象，所以不会有 getName 方法。
