### ISSUE TITLE
请问什么时候写个异步教程，从定时器到async

### ISSUE THREAD

**Issue by wangcanqiang** [mqyqingfeng/Blog#50]
如题，请问一下什么时候写个异步教程，从定时器到async

**Comment by mqyqingfeng** [comment]
@wangcanqiang 感谢建议哈，可能不会单独写个异步系列，但是从定时器到 async 的内容在以后的文章中应该都有涉及，定时器可能在深入系列第二季的文章中，async 会在 ES6 系列文章中，欢迎关注哈~

**Comment by wangcanqiang** [comment]
我是觉得这些内容是异步编程逐步发展的过程，完全可以做一个专题，现有网上资料都太分散，还没找到一个关于这的系统的教程，你可以考虑下，放在以后也行，就是这样还是太分散，没有专题学习的效果好。

**Comment by mqyqingfeng** [comment]
@wangcanqiang 嗯，我会认真考虑这个建议的，此外我看过一个异步系列的教程，[深入理解 JavaScript 异步](https://github.com/wangfupeng1988/js-async-tutorial)，你可以参考一下。
