### ISSUE TITLE
第一版debounce有一点问题

### ISSUE THREAD

**Issue by magentaqin** [mqyqingfeng/Blog#59]
container.onmousemove = debounce(getUserAction, 1000)是不是应该是container.onmousemove = debounce(getUserAction, 1000)()，不然return的闭包无法执行。已经试过了。望作者修改过来。

**Comment by mqyqingfeng** [comment]
@magentaqin  [demo 在这里~](https://github.com/mqyqingfeng/Blog/tree/master/demos/debounce)

**Comment by magentaqin** [comment]
谢谢啦。貌似是我弄错了。

2017-12-01 12:20 GMT+08:00 冴羽 <notifications@github.com>:
