### ISSUE TITLE
函数调用讲解

### ISSUE THREAD

**Issue by wannebe** [mqyqingfeng/Blog#61]
我觉得你说的那本书中解释尾递归时讲述的函数创建调用不如阮一峰大大在《ES6 标准入门》中解释的好：
函数调用会在内存中形成一个“调用记录”，又称“调用帧”（call frame）,保存调用的位置和内部变量等信息。如果函数A的内部调用函数B，那么A对的调用帧上方还会形成一个B的调用帧，等到B的运行结束，将结果返回给A，B的调用帧才会消失，如果B还调用C，还会有C的调用帧，所有调用帧就形成了“调用栈”（call stack）.重点在这里，尾调用就是说函数最后一部操作不需要保留外层函数的调用帧，外层调用帧保存的调用位置、内部变量不再需要，这时就会直接用内层函数调用帧取带外层函数。这也是不要过多使用函数闭包的原因了，闭包就会引用外层函数变量，导致内存溢出。另外就说这个尾调用外加尾递归包含挺多东西的，至少包含函数创建、调用、闭包，内存，调用栈，消息队列

**Comment by mqyqingfeng** [comment]
@wannebe 你是说这篇文章吗 [JavaScript专题之递归](https://github.com/mqyqingfeng/Blog/issues/49) ？不介意的话，我将其补充到评论中~

关于这个解释还蛮见仁见智的，阮一峰大大的这个我也看了，最早是在这一篇中 [尾调用优化](http://www.ruanyifeng.com/blog/2015/04/tail-call.html)，一个是调用帧的概念，因为我并没有从其他文章中看到过这个概念，所以我直接使用执行上下文和执行上下文栈来进行表示。关于尾递归不会增加多的调用帧，其实想表达意思是一样的，这个就看读者的见解了。

还有函数创建、调用、闭包、内存、调用栈这些内容，不止是尾调用和尾递归，其实任何一个函数中调用其他函数都会涉及到这些内容，这些在我之前的内容中有所涉及：

2. [JavaScript深入之词法作用域和动态作用域](https://github.com/mqyqingfeng/Blog/issues/3)
3. [JavaScript深入之执行上下文栈](https://github.com/mqyqingfeng/Blog/issues/4)
4. [JavaScript深入之变量对象](https://github.com/mqyqingfeng/Blog/issues/5)
5. [JavaScript深入之作用域链](https://github.com/mqyqingfeng/Blog/issues/6)
6. [JavaScript深入之从ECMAScript规范解读this](https://github.com/mqyqingfeng/Blog/issues/7)
7. [JavaScript深入之执行上下文](https://github.com/mqyqingfeng/Blog/issues/8)
8. [JavaScript深入之闭包](https://github.com/mqyqingfeng/Blog/issues/9)
