### ISSUE TITLE
新年快乐，2018 年让我们相互勉励，共同进步~ 

### ISSUE THREAD

**Issue by mqyqingfeng** [mqyqingfeng/Blog#66]
感谢大家过去一年的陪伴，我不算是一个能坚持的人，正是大家的存在让我一直有动力写下去，非常感谢你们~

最近比较忙啦，文章也没能及时发，还积攒了几天的留言，我会尽快回复大家的~

祝大家 2018 年，身体健康，事业顺利，单身的都能脱单，不单身的……嗯，不用管啦~

[]\~(￣▽￣)\~*

**Comment by jawil** [comment]
我都积攒了好久==，现在希望能保证的就是每个月写一篇文章，慢慢的会偏业务了，2333~

**Comment by mqyqingfeng** [comment]
@jawil 我很期待你写业务实践相关的文章呀~

**Comment by jawil** [comment]
现在纯业务，还是小菜鸟，哈哈，基层干起，暂时没啥实践，还在熟悉学习当中~@mqyqingfeng

**Comment by Xchen1995** [comment]
祝顺利！

**Comment by Nealyang** [comment]
加油加油~
