### ISSUE TITLE
对这样写博客感兴趣

### ISSUE THREAD

**Issue by bigdots** [mqyqingfeng/Blog#72]
这样使用issue，别人提的issue怎么办，比如我提的这个

**Comment by bigdots** [comment]
可以删除或者规范吗

**Comment by liuliangsir** [comment]
不能删除，不过可以关闭，而且尽量不要提没有意义的 issue 吧

**Comment by Ley130607** [comment]
真行

**Comment by mqyqingfeng** [comment]
@bigdots 你不是第一个提 issue 的啦~

<img width="609" alt="default" src="https://user-images.githubusercontent.com/11458263/37136599-38d22f0e-22dd-11e8-99cc-7238a97d185d.png">

你可以在这里点击 close 查看已经关闭的 issue
