### ISSUE TITLE
ES6专题

### ISSUE THREAD

**Issue by YangGoldDragon** [mqyqingfeng/Blog#74]
说好的ES6专题呢，等的好辛苦。求更新！

**Comment by Rudy24** [comment]
可以先看看阮一峰写的，很详细，

发自我的 iPhone

**Comment by YangGoldDragon** [comment]
我看过了，但是感觉还是不能很好的理解promise并使用它，还是喜欢你的讲解，通俗易懂，坐等你之后的更新。

**Comment by mqyqingfeng** [comment]
@YangGoldDragon 哈哈，我也卡在 promise 上了，文章是准备从零实现一个 promise ，不过需要参考和阅读的东西有点多，写了一份草稿，感觉不行，想再看看 Q 或者其他库的源码再重写一遍，这个拖得比较久，加上最近事情很多，所以让你久等了，很抱歉啦~
