### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by EtheriousNatsu** [mqyqingfeng/Blog#80]
作者你好:
      我也是javascript新手，看了你的博客，受益良多。我有2个问题，请回答下我，谢谢。
      1、可以开一个ES6的专题吗？
      2、现在这个时间节点是直接学习ES6还是先学ES5

**Comment by fws407296762** [comment]
1、ES6 专题有阮一峰的《ES6入门标准》；
2、学习技术没时间节点，现在照样很多人学 C++。ES6 是在 ES5 的基础上发展出来的，类似 CSS3 和 CSS2 的关系，没有先学哪个道理，只有你在业务中是否需要用到哪个API。
多说一句：如果你是够大胆或者放得开的话，可以出去投几个简历试试，多出去多和一些公司的面试官聊聊，你可以知道比这里更多的东西。比如你第二个问题可以多问几个有经验的面试官。面试比做项目学到的东西更多！！

**Comment by Latube** [comment]
附上阮一峰的 ES6 地址<http://es6.ruanyifeng.com/>
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 松鼠闹IT<mailto:notifications@github.com>
发送时间: 2018年4月26日 17:51
主题: Re: [mqyqingfeng/Blog] ES6 (#80)


1、ES6 专题有阮一峰的《ES6入门标准》；
2、学习技术没时间节点，现在照样很多人学 C++。ES6 是在 ES5 的基础上发展出来的，类似 CSS3 和 CSS2 的关系，没有先学哪个道理，只有你在业务中是否需要用到哪个API。
多说一句：如果你是够大胆或者放得开的话，可以出去投几个简历试试，多出去多和一些公司的面试官聊聊，你可以知道比这里更多的东西。比如你第二个问题可以多问几个有经验的面试官。面试比做项目学到的东西更多！！

―

**Comment by mqyqingfeng** [comment]
@EtheriousNatsu 你好呀，接下来会发布的就是 ES6 专题，现在还在准备中，ES6 专题的思路也是从 ES6 中找一些点进行探究，完整而系统的 ES6 学习还是要看 阮一峰老师的 《ES6 入门标准》，@fws407296762  @Latube 都提到了这本书，不过这本书读起来可能稍微有点枯燥，你也可以读 Nicholas C.Zakas 的 《深入理解 ES6》，会白话文一些，建议还是先看看这两本书中的一本，再看 ES6 系列。

关于第二个问题，反而因为是在这个时间节点，两者更都是要学的，毕竟 ES5 是基础，ES6 已经是大势所趋，如果你大致翻完了红宝书或者犀牛书，大部分都能理解，那就可以考虑学习 ES6 啦

**Comment by swust-xiaoj** [comment]
[红宝书](https://item.jd.com/10951037.html)
[犀牛书](https://item.jd.com/10974436.html)

**Comment by EtheriousNatsu** [comment]
@swust-xiaoj  谢谢
