### ISSUE TITLE
请问通常方法写在child组件本身好还是都放在parent组件再去调用好？

### ISSUE THREAD

**Issue by ZhenWang-Jen** [mqyqingfeng/Blog#89]
如题。可以的话谢谢回复！

**Comment by mqyqingfeng** [comment]
@ZhenWang-Jen 你是说在 React 项目中吗？如果 child 组件之间相互独立，没有联系，我觉得放在 child 组件本身就很不错，如果需要共同使用一份数据，我更倾向于放在 parent 组件中。

不过在实际的开发中，因为经常会遇到可恶的产品经理乱改需求！！！乱改需求！！！乱改需求！！！ 本来应该是相互独立的组件，但是却不得不用到同一份数据，所以个人更倾向于写到 parent 组件中，但这又会导致 parent 组件代码量很大……

总之我也觉得这是一个很难的问题，需要开发者自己把握……

**Comment by wuyunqiang** [comment]
独立的放到组件内部 共同的放到parent中
如果很多功能独立的组件需要共享数据 那应该将数据存储在某一处然后每个组件单独读取啊或者直接使用redux进行数据流管理。
