### ISSUE TITLE
博主，有一个关于改变this指向的问题想要问问你

### ISSUE THREAD

**Issue by yangjunfocus** [mqyqingfeng/Blog#97]
函数1:`function bindThis(func, context) {
    return function() {
            return func.apply(context, arguments);
        };
}`
函数2：`function bindThis(func, context) {
            return func.apply(context, arguments);
}`

这样都能实现改变this的指向，为什么函数1 要多一层return，有什么区别？
希望博主不吝赐教！感谢！

**Comment by BuptStEve** [comment]
骚年听说过高阶函数么？

**Comment by shadowprompt** [comment]
第二种的话bindThis直接返回的是func函数运行的结果，而不是返回的函数。

**Comment by mqyqingfeng** [comment]
```jsx
<button onClick={this.handleClick.bind(this)}></button>
```

比如 React 这里绑定事件处理函数需要指定 this 后依然返回一个函数，其实效果就等同于函数1

```jsx
<button onClick={bindThis(handleClick, this)}></button>
```
